repos:
  - repo: https://github.com/google/yamlfmt
    rev: v0.14.0
    hooks:
      - id: yamlfmt
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.5.26
    hooks:
      - id: uv-lock
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.9.4
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix]
      # Run the formatter.
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    # mypy version
    rev: v1.14.1
    hooks:
      - id: mypy
        args: [--strict, --ignore-missing-imports]
